parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: org_incongru_laboiteason
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 7bf1afd65bf6b314f2d3b4625c06ea9f94d17837
    database_path: null
